version: '3'

services:
  publisher:
    build:
      context: .
      dockerfile: Dockerfile.publisher
    networks:
      - mynetwork

  subscriber:
    build:
      context: .
      dockerfile: Dockerfile.subscriber
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
